server:
  port: 7050

spring:
  config:
    import:
      - optional:file:./secrets-local.properties
  application:
    name: pix-key-registration
  mvc:
    static-path-pattern: /swagger*
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        ### https://jdbc.postgresql.org/documentation/use/#connection-parameters
        reWriteBatchedInserts: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        generate_statistics: false
        format_sql: false
        jdbc:
          batch_size: 25
        order_inserts: true
    open-in-view: false
  task:
    execution:
      pool:
        queue-capacity: 10000
  flyway:
    url: ${database.url}
    user: ${database.username}
    password: ${database.password}
    locations: db.migration
    baseline-on-migrate: true
springdoc:
  swagger-ui:
    path: /docs
    protocol: http
app:
  person:
    legal-person-limit-account: 5
    natural-person-limit-account: 1
    pix-keys-legal-person-limit: 20
    pix-keys-natural-person-limit: 5